name: beaglebone-blue-kernel
version: 4.4.91-1
summary: Beaglebone kernel built from source
description: This is the official Beaglebone kernel built from source
type: kernel
architectures: [ armhf ]

parts:
    kernel:
        plugin: kernel
        source: https://github.com/beagleboard/linux.git
        source-branch: "4.4"
        source-type: git
        kdefconfig: [bb.org_defconfig]
        kconfigs:
            - CONFIG_LOCALVERSION="-beaglebone-ubuntucore"
            - CONFIG_DEBUG_INFO=n
            - CONFIG_SQUASHFS=m
            - CONFIG_BLK_DEV_LOOP=m
            - CONFIG_CONFIGFS_FS=y
            - CONFIG_MD=y
            - CONFIG_BLK_DEV_DM=y
            - CONFIG_BLK_DEV_RAM=y
            - CONFIG_BLK_DEV_RAM_SIZE=65536
            - CONFIG_TMPFS_POSIX_ACL=y
            - CONFIG_DEVTMPFS=y
            - CONFIG_DEVTMPFS_MOUNT=y
            - CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
            - CONFIG_RFKILL_LEDS=y
            - CONFIG_LEDS_TRIGGERS=y

        kernel-initrd-modules:
            - squashfs
        kernel-image-target: zImage
        kernel-device-trees:
            - am335x-boneblue
        build-packages: [bc, kmod, cpio]
